/*!
 * Axum route handlers
 */
use axum::{routing::get, Router};
use std::sync::Arc;

use super::state;

// Exports
mod health;
mod users;
mod categories;
mod points;
mod rewards;

/// Configure api routes
pub(crate) fn init(state: Arc::<state::State>) -> Router {

  // TODO: layer in security
  // let sensitive_headers = vec![header::AUTHORIZATION, header::COOKIE].into();

  // Disabling CORS across my routes for now
  // TODO: revisit where to enable CORS
  // let cors = cors::CorsLayer::new()
  //   .allow_methods([Method::GET, Method::POST])
  //   .allow_origin(cors::Any)
  //   .allow_headers([header::CONTENT_TYPE]);

  // Define the routes
  Router::new()
    .route("/health",
      get(health::get))

    // Users routes
    .route("/users",
      get(users::get_all).post(users::create))
    .route("/users/{opt}",
      get(users::get_by_id).put(users::update_by_id).delete(users::delete_by_id))

    // Categories routes
    .route("/categories",
      get(categories::get).post(categories::create))
    .route("/categories/{opt}",
      get(categories::get_by_id).put(categories::update_by_id).delete(categories::delete_by_id))

    // Points points
    .route("/points",
      get(points::get).post(points::create))
    .route("/points/{opt}",
      get(points::get_by_id).put(points::update_by_id).delete(points::delete_by_id))
 
    // Rewards routes
    .route("/rewards",
      get(rewards::get).post(rewards::create))
    .route("/rewards/{opt}",
      get(rewards::get_by_id).put(rewards::update_by_id).delete(rewards::delete_by_id))
    // .layer(cors)
    
    // Add the Fastrace layer for observability
    .layer(fastrace_axum::FastraceLayer)
    .with_state(state)
}

// -------------------------------------------------------------------------------------------------
// Custom rejection for JSON payloads so that we can return a consistent error response whether it
// was generated by an extractor early on or by application code during the handling of the request.
// -------------------------------------------------------------------------------------------------

// Converts into an `errors::Error` in the extraction rejection path
#[derive(axum::extract::FromRequest)]
#[from_request(via(axum::Json), rejection(crate::errors::Error))]
pub struct Json<T>(T);

// Converts to `IntoResponse` in the positve extraction path
impl<T: serde::Serialize> axum::response::IntoResponse for Json<T> {
    fn into_response(self) -> axum::response::Response {
        let Self(value) = self;
        axum::Json(value).into_response()
    }
}
