
-- users
CREATE TABLE IF NOT EXISTS users (
  id INTEGER AUTO INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- points
CREATE TABLE IF NOT EXISTS points (
  id INTEGER AUTO INCREMENT PRIMARY KEY,
  value INTEGER NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) on DELETE CASCADE,
  category_id INTEGER NOT NULL DEFAULT 0 REFERENCES categories(id) on DELETE SET DEFAULT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- categories
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER AUTO INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- rewards
CREATE TABLE IF NOT EXISTS rewards (
  id INTEGER AUTO INCREMENT PRIMARY KEY,
  value INTEGER NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) on DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
