-- Add down migration script here
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS password;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS point;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS category_parent;
DROP TABLE IF EXISTS action;
DROP TABLE IF EXISTS reward;